server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiandao?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl